const express=require('express');const cors=require('cors');const helmet=require('helmet');const rateLimit=require('express-rate-limit');const crypto=require('crypto');const net=require('net');const {WebSocketServer}=require('ws');
const config=require('./config');const store=require('./storage');const security=require('./security');const detection=require('./detection');
const app=express();app.disable('x-powered-by');app.use(helmet());app.use(cors({origin:(origin,cb)=>!origin||config.corsOrigins.includes(origin)?cb(null,true):cb(new Error('Origin not allowed'))}));app.use(express.json({limit:'1mb'}));
function normalize(input){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Event must be an object');const severity=String(input.severity||'INFO').toUpperCase();if(!['CRITICAL','HIGH','MEDIUM','LOW','INFO'].includes(severity))throw Error('Invalid severity');const timestamp=input.timestamp||new Date().toISOString();if(Number.isNaN(Date.parse(timestamp)))throw Error('Invalid timestamp');const ip=String(input.source_ip||input.sourceIp||'unknown');if(ip!=='unknown'&&net.isIP(ip)===0)throw Error('Invalid source_ip');const text=(v,n)=>String(v??'').slice(0,n);return{id:Date.now()+'-'+crypto.randomBytes(4).toString('hex'),timestamp:new Date(timestamp).toISOString(),severity,category:text(input.category||'general',100),source_ip:ip,message:text(input.message||'Event received',1000),hostname:text(input.hostname||'unknown',255)}} 
const clients=new Set();function broadcast(x){const s=JSON.stringify(x);for(const ws of clients)if(ws.readyState===1)ws.send(s)}
app.get('/health',(_q,r)=>{store.prune();r.json({status:'ok',service:'sentinel-siem',version:'3.0.0',events:store.getEvents().length,alerts:store.getAlerts().filter(a=>a.status==='NEW').length})});
app.post('/api/auth/login',rateLimit({windowMs:900000,limit:10,standardHeaders:true,legacyHeaders:false}), (req,res)=>{const user=security.login(req.body?.username,req.body?.password);if(!user)return res.status(401).json({error:'Invalid credentials'});store.addAudit({id:crypto.randomUUID(),timestamp:new Date().toISOString(),action:'LOGIN_SUCCESS',actor:user.username});res.json({token:security.token(user),user})});
app.get('/api/auth/me',security.auth,(req,res)=>res.json({user:req.user}));
app.post('/api/ingest/event',security.apiKey,(req,res)=>{try{const e=normalize(req.body);store.addEvents([e]);const alert=detection.evaluate(e,store.getEvents());if(alert){store.addAlert(alert);broadcast({type:'alert',alert})}broadcast({type:'event',event:e});res.status(201).json({event:e,alert})}catch(err){res.status(400).json({error:err.message})}});
app.post('/api/ingest/bulk',security.apiKey,(req,res)=>{try{if(!Array.isArray(req.body)||req.body.length>1000)throw Error('Payload must contain 1-1000 events');const items=req.body.map(normalize);store.addEvents(items);items.forEach(e=>{const a=detection.evaluate(e,store.getEvents());if(a){store.addAlert(a);broadcast({type:'alert',alert:a})}broadcast({type:'event',event:e})});res.status(201).json({count:items.length})}catch(err){res.status(400).json({error:err.message})}});
app.get('/api/events',security.auth,(req,res)=>{store.prune();let result=[...store.getEvents()].reverse();if(req.query.severity)result=result.filter(e=>e.severity===String(req.query.severity).toUpperCase());if(req.query.category)result=result.filter(e=>e.category===req.query.category);if(req.query.search){const q=String(req.query.search).toLowerCase();result=result.filter(e=>JSON.stringify(e).toLowerCase().includes(q))}const offset=Math.max(0,Number(req.query.offset)||0),limit=Math.min(200,Math.max(1,Number(req.query.limit)||50));res.json({events:result.slice(offset,offset+limit),total:result.length})});
app.get('/api/alerts',security.auth,(req,res)=>res.json({alerts:store.getAlerts().filter(a=>!req.query.status||a.status===req.query.status)}));
app.patch('/api/alerts/:id',security.auth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'Forbidden'});if(!['NEW','ACKNOWLEDGED','RESOLVED','CLOSED'].includes(req.body?.status))return res.status(400).json({error:'Invalid status'});const a=store.updateAlert(req.params.id,req.body.status,req.user.username);if(!a)return res.status(404).json({error:'Alert not found'});store.addAudit({id:crypto.randomUUID(),timestamp:new Date().toISOString(),action:'ALERT_STATUS_CHANGE',actor:req.user.username,target:a.id,status:a.status});broadcast({type:'alert.updated',alert:a});res.json({alert:a})});
app.get('/api/stats/summary',security.auth,(_q,res)=>{const es=store.getEvents(),as=store.getAlerts();res.json({totalEvents:es.length,openAlerts:as.filter(a=>a.status==='NEW').length,criticalEvents:es.filter(e=>e.severity==='CRITICAL').length,highEvents:es.filter(e=>e.severity==='HIGH').length,sources:new Set(es.map(e=>e.source_ip)).size})});
app.get('/api/audit',security.auth,(req,res)=>res.json({audit:store.getAudit().slice(-100).reverse()}));app.use('/api',(_q,r)=>r.status(404).json({error:'Not Found'}));
app.use(express.static(require('path').join(__dirname,'..','frontend','dist')));app.get('*',(_q,r)=>r.sendFile(require('path').join(__dirname,'..','frontend','dist','index.html')));
const server=app.listen(config.port,()=>console.log(`Sentinel SIEM listening on ${config.port}`));const wss=new WebSocketServer({noServer:true});server.on('upgrade',(req,socket,head)=>{if(!req.url.startsWith('/ws'))return socket.destroy();try{security.auth({headers:{authorization:'Bearer '+new URL(req.url,'http://localhost').searchParams.get('token')}},{status:()=>({}),json:()=>{}} ,()=>{})}catch{}const token=new URL(req.url,'http://localhost').searchParams.get('token');try{require('jsonwebtoken').verify(token,config.jwtSecret,{issuer:'sentinel-siem'})}catch{socket.write('HTTP/1.1 401 Unauthorized\\r\\n\\r\\n');return socket.destroy()}wss.handleUpgrade(req,socket,head,ws=>wss.emit('connection',ws,req))});wss.on('connection',ws=>{clients.add(ws);ws.on('close',()=>clients.delete(ws));});
process.on('SIGTERM',()=>server.close(()=>process.exit(0)));