const postgres=require('postgres');
const crypto=require('crypto');
const {databaseUrl,retentionDays,adminUser,adminPasswordHash,ingestKey}=require('./config');
if(!databaseUrl)throw new Error('DATABASE_URL is required for PostgreSQL storage');
const sql=postgres(databaseUrl,{max:5,connect_timeout:10,idle_timeout:20,prepare:false});
const q=(text,values=[])=>sql.unsafe(text,values);
const ready=(async()=>{
 await q(`
CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,timestamp TIMESTAMPTZ NOT NULL,severity TEXT NOT NULL,category TEXT NOT NULL,source_ip TEXT NOT NULL,message TEXT NOT NULL,hostname TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_events_timestamp ON events(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_events_severity_timestamp ON events(severity,timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_events_source_timestamp ON events(source_ip,timestamp DESC);
CREATE TABLE IF NOT EXISTS alerts(id TEXT PRIMARY KEY,created_at TIMESTAMPTZ NOT NULL,source_ip TEXT NOT NULL,severity TEXT NOT NULL,status TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL,count INTEGER NOT NULL,updated_at TIMESTAMPTZ,updated_by TEXT,rule_key TEXT);
CREATE INDEX IF NOT EXISTS idx_alerts_status_created ON alerts(status,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_rule_status ON alerts(rule_key,status);
CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('admin','analyst')),enabled BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS ingest_keys(id TEXT PRIMARY KEY,name TEXT NOT NULL,key_hash TEXT NOT NULL UNIQUE,key_prefix TEXT NOT NULL,enabled BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL,rotated_at TIMESTAMPTZ,revoked_at TIMESTAMPTZ,last_used_at TIMESTAMPTZ,created_by TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS detection_rules(rule_key TEXT PRIMARY KEY,name TEXT NOT NULL,description TEXT NOT NULL,enabled BOOLEAN NOT NULL DEFAULT TRUE,window_ms BIGINT NOT NULL,threshold INTEGER NOT NULL,severities JSONB NOT NULL,categories JSONB NOT NULL,message_pattern TEXT NOT NULL,alert_severity TEXT NOT NULL,title TEXT NOT NULL,updated_at TIMESTAMPTZ NOT NULL,updated_by TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit(id TEXT PRIMARY KEY,timestamp TIMESTAMPTZ NOT NULL,action TEXT NOT NULL,actor TEXT NOT NULL,target TEXT,status TEXT);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON audit(timestamp DESC);`);
 if(adminPasswordHash)await q('INSERT INTO users(username,password_hash,role,enabled,created_at,updated_at) VALUES($1,$2,$3,TRUE,NOW(),NOW()) ON CONFLICT(username) DO NOTHING',[adminUser,adminPasswordHash,'admin']);
 if(ingestKey){const h=crypto.createHash('sha256').update(ingestKey).digest('hex');await q('INSERT INTO ingest_keys(id,name,key_hash,key_prefix,enabled,created_at,created_by) SELECT $1,$2,$3,$4,TRUE,NOW(),$5 WHERE NOT EXISTS(SELECT 1 FROM ingest_keys)',[crypto.randomUUID(),'bootstrap',h,ingestKey.slice(0,8),adminUser]);}
 await q("INSERT INTO detection_rules(rule_key,name,description,enabled,window_ms,threshold,severities,categories,message_pattern,alert_severity,title,updated_at,updated_by) VALUES('auth-bruteforce-v1','Authentication brute force','Repeated failed authentication attempts from one source.',TRUE,300000,5,'[\"HIGH\",\"CRITICAL\"]'::jsonb,'[\"ssh\",\"login\",\"authentication\"]'::jsonb,'/failed|invalid|denied/i','CRITICAL','Possible brute-force authentication attack',NOW(),'system') ON CONFLICT(rule_key) DO NOTHING");
})();
const ensure=()=>ready;
async function getEvents(o={}){await ensure();const {search='',severity='',category='',source_ip='',since='',limit,offset=0}=o;const c=[],v=[];const add=(x,s)=>{v.push(x);c.push(s.replaceAll('?', '$'+v.length))};if(search)add('%'+search.toLowerCase()+'%','(lower(message) LIKE ? OR lower(category) LIKE ? OR lower(source_ip) LIKE ? OR lower(hostname) LIKE ?)');if(search){v.splice(v.length-1,0,v[v.length-1],v[v.length-1],v[v.length-1]);}if(severity)add(severity,'severity=?');if(category)add(category,'category=?');if(source_ip)add(source_ip,'source_ip=?');if(since)add(since,'timestamp>=?');const w=c.length?' WHERE '+c.join(' AND '):'';const total=Number((await q('SELECT COUNT(*) count FROM events'+w,v))[0].count);const rows=limit===undefined?await q('SELECT * FROM events'+w+' ORDER BY timestamp DESC',v):await q('SELECT * FROM events'+w+' ORDER BY timestamp DESC LIMIT $'+(v.length+1)+' OFFSET $'+(v.length+2),[...v,limit,offset]);return {events:rows,total};}
async function getRecentEvents(ip,since){await ensure();return q('SELECT * FROM events WHERE source_ip=$1 AND timestamp>=$2 ORDER BY timestamp DESC',[ip,since]);}
async function getAlerts(status){await ensure();return status?q('SELECT * FROM alerts WHERE status=$1 ORDER BY created_at DESC',[status]):q('SELECT * FROM alerts ORDER BY created_at DESC');}
async function getActiveAlert(rule,ip){await ensure();const r=await q("SELECT * FROM alerts WHERE rule_key=$1 AND source_ip=$2 AND status IN('NEW','ACKNOWLEDGED') ORDER BY created_at DESC LIMIT 1",[rule,ip]);return r[0]||null;}
async function getAudit(){await ensure();return q('SELECT * FROM audit ORDER BY timestamp DESC LIMIT 100');}
async function getUser(u){await ensure();const r=await q('SELECT id,username,password_hash,role,enabled,created_at,updated_at FROM users WHERE username=$1 AND enabled=TRUE',[u]);return r[0]||null;}
async function listUsers(){await ensure();return q('SELECT id,username,role,enabled,created_at,updated_at FROM users ORDER BY username');}
async function addUser(u){await ensure();const r=await q('INSERT INTO users(username,password_hash,role,enabled,created_at,updated_at) VALUES($1,$2,$3,TRUE,NOW(),NOW()) RETURNING id',[u.username,u.password_hash,u.role]);return r[0].id;}
async function setUserEnabled(id,en){await ensure();const r=await q('UPDATE users SET enabled=$1,updated_at=NOW() WHERE id=$2 RETURNING id,username,role,enabled,created_at,updated_at',[Boolean(en),id]);return r[0]||null;}
async function getIngestKeys(){await ensure();return q('SELECT id,name,key_prefix,enabled,created_at,rotated_at,revoked_at,last_used_at,created_by FROM ingest_keys ORDER BY created_at DESC');}
async function verifyIngestKey(raw){await ensure();const h=crypto.createHash('sha256').update(String(raw||'')).digest('hex');const r=await q('SELECT id,name,key_prefix FROM ingest_keys WHERE key_hash=$1 AND enabled=TRUE AND revoked_at IS NULL',[h]);if(!r[0])return null;await q('UPDATE ingest_keys SET last_used_at=NOW() WHERE id=$1',[r[0].id]);return r[0];}
async function createIngestKey(k){await ensure();const t=new Date().toISOString();await q('INSERT INTO ingest_keys(id,name,key_hash,key_prefix,enabled,created_at,last_used_at,created_by) VALUES($1,$2,$3,$4,TRUE,$5,NULL,$6)',[k.id,k.name,k.hash,k.raw.slice(0,8),t,k.created_by]);return {id:k.id,name:k.name,key_prefix:k.raw.slice(0,8),created_at:t};}
async function revokeIngestKey(id){await ensure();const t=new Date().toISOString();const r=await q('UPDATE ingest_keys SET enabled=FALSE,revoked_at=$1,rotated_at=$1 WHERE id=$2 RETURNING id,name,key_prefix,enabled,created_at,rotated_at,revoked_at,last_used_at,created_by',[t,id]);return r[0]||null;}
async function listRules(){await ensure();return (await q('SELECT * FROM detection_rules ORDER BY rule_key')).map(r=>({...r,enabled:Boolean(r.enabled),severities:r.severities,categories:r.categories}));}
async function getRules(){return (await listRules()).filter(r=>r.enabled);}
async function upsertRule(r,user){await ensure();const t=new Date().toISOString();const x=await q('INSERT INTO detection_rules(rule_key,name,description,enabled,window_ms,threshold,severities,categories,message_pattern,alert_severity,title,updated_at,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9,$10,$11,$12,$13) ON CONFLICT(rule_key) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,enabled=EXCLUDED.enabled,window_ms=EXCLUDED.window_ms,threshold=EXCLUDED.threshold,severities=EXCLUDED.severities,categories=EXCLUDED.categories,message_pattern=EXCLUDED.message_pattern,alert_severity=EXCLUDED.alert_severity,title=EXCLUDED.title,updated_at=EXCLUDED.updated_at,updated_by=EXCLUDED.updated_by RETURNING *',[r.rule_key,r.name,r.description,Boolean(r.enabled),r.window_ms,r.threshold,JSON.stringify(r.severities),JSON.stringify(r.categories),r.message_pattern,r.alert_severity,r.title,t,user]);return x[0];}
async function getStats(){await ensure();return (await q('SELECT (SELECT COUNT(*)::int FROM events) "totalEvents",(SELECT COUNT(*)::int FROM events WHERE severity=\'CRITICAL\') "criticalEvents",(SELECT COUNT(*)::int FROM events WHERE severity=\'HIGH\') "highEvents",(SELECT COUNT(DISTINCT source_ip)::int FROM events) sources,(SELECT COUNT(*)::int FROM alerts WHERE status=\'NEW\') "openAlerts"'))[0];}
async function addEvents(items){await ensure();for(const e of items)await q('INSERT INTO events(id,timestamp,severity,category,source_ip,message,hostname) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO UPDATE SET timestamp=EXCLUDED.timestamp,severity=EXCLUDED.severity,category=EXCLUDED.category,source_ip=EXCLUDED.source_ip,message=EXCLUDED.message,hostname=EXCLUDED.hostname',[e.id,e.timestamp,e.severity,e.category,e.source_ip,e.message,e.hostname]);}
async function addAlert(a){await ensure();await q('INSERT INTO alerts(id,created_at,source_ip,severity,status,title,description,count,updated_at,updated_by,rule_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,updated_at=EXCLUDED.updated_at,updated_by=EXCLUDED.updated_by',[a.id,a.created_at,a.source_ip,a.severity,a.status,a.title,a.description,a.count,a.updated_at||null,a.updated_by||null,a.rule_key||null]);}
async function updateAlert(id,status,user){await ensure();const r=await q('UPDATE alerts SET status=$1,updated_at=NOW(),updated_by=$2 WHERE id=$3 RETURNING *',[status,user,id]);return r[0]||null;}
async function addAudit(a){await ensure();await q('INSERT INTO audit(id,timestamp,action,actor,target,status) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status',[a.id,a.timestamp,a.action,a.actor,a.target||null,a.status||null]);}
async function prune(){await ensure();const cut=new Date(Date.now()-retentionDays*86400000).toISOString();await q('DELETE FROM events WHERE timestamp<$1',[cut]);await q('DELETE FROM alerts WHERE id IN(SELECT id FROM alerts ORDER BY created_at DESC OFFSET 5000)');await q('DELETE FROM audit WHERE id IN(SELECT id FROM audit ORDER BY timestamp DESC OFFSET 5000)');}
async function health(){await ensure();await q('SELECT 1');return true;}
async function close(){await sql.end({timeout:5});}
module.exports={getEvents,getRecentEvents,getAlerts,getActiveAlert,getAudit,getStats,addEvents,addAlert,updateAlert,addAudit,prune,health,getUser,listUsers,addUser,setUserEnabled,getIngestKeys,verifyIngestKey,createIngestKey,revokeIngestKey,listRules,getRules,upsertRule,close};
